services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: gerenciador-contatos:latest
    container_name: gc-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - gc-network

  nginx:
    image: nginx:alpine
    container_name: gc-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gc-network

networks:
  gc-network:
    driver: bridge
